#ifndef __glCmdAndStructPrint2_h__2013_10_28__
#define __glCmdAndStructPrint2_h__2013_10_28__

//集中管理模式，共享打印机信息，操作类型
enum REQ_PRINTSHAREPRINTERINFO_TYPE
{
	REQ_SHARE_FROM_DB = 0,		//从数据库中请求
	REQ_SHARE_ADD_BY_PRT = 1,//打印站点自动添加
	REQ_SHARE_ADD_BY_TOOL = 2,	//通过工具自动添加
	REQ_SHARE_CHECK_PRT_INFO = 3,	//检测打印站点配置信息
	REQ_SHARE_DEL_BY_PRT= 4,	//删除打印站点配置信息
	REQ_SHARE_DEL_BY_TOOL= 5	//删除打印站点配置信息
};


#define  IST_BASE_6000	6000
#define  WM_IST_PRINT2		WM_USER + IST_BASE_6000

//打印日志-成绩打印
#define WM_REQ_PRINT_LOG_TRANSCRIPT				WM_IST_PRINT2 + 60
#define WM_REQ_PRINT_LOG_FILE_TRANSCRIPT		WM_IST_PRINT2 + 61
#define WM_REQ_PRINT_LOG_FILE_END_TRANSCRIPT	WM_IST_PRINT2 + 62
#define WM_PUSH_PRINT_LOG_FILE_TRANSCRIPT		WM_IST_PRINT2 + 63
#define WM_ALL_PRINT_LOG_END_TRANSCRIPT			WM_IST_PRINT2 + 64
#define WM_PRINT_FLAG_TRANSCRIPT				WM_IST_PRINT2 + 65
#define WM_REQ_PRINT_LOG_TRANSCRIPT_ENTRUST		WM_IST_PRINT2 + 66


//打印日志-准考证打印
#define WM_REQ_PRINT_LOG_ADMISSION				WM_IST_PRINT2 + 70
#define WM_REQ_PRINT_LOG_FILE_ADMISSION			WM_IST_PRINT2 + 71
#define WM_REQ_PRINT_LOG_FILE_END_ADMISSION		WM_IST_PRINT2 + 72
#define WM_PUSH_PRINT_LOG_FILE_ADMISSION		WM_IST_PRINT2 + 73
#define WM_ALL_PRINT_LOG_END_ADMISSION			WM_IST_PRINT2 + 74
#define WM_PRINT_FLAG_ADMISSION					WM_IST_PRINT2 + 75


#define WM_PRINT_STATION_CHARGE_ON_PRINT_TRANSCRIPT		WM_IST_PRINT2 + 81 //打印站点成绩打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_ADMISSION		WM_IST_PRINT2 + 82 //打印站点准考证打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_USBPRINT		WM_IST_PRINT2 + 83 //打印站点usb打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_LEAVESCHOOL	WM_IST_PRINT2 + 84 //打印站点离校单打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_CLOUD			WM_IST_PRINT2 + 85 //打印站点云打印计费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_NOTICE			WM_IST_PRINT2 + 86 //打印站点公告打印计费

//打印日志-USB打印
#define WM_REQ_PRINT_LOG_USBPRINT				WM_IST_PRINT2 + 90
#define WM_REQ_PRINT_LOG_FILE_USBPRINT			WM_IST_PRINT2 + 91
#define WM_REQ_PRINT_LOG_FILE_END_USBPRINT		WM_IST_PRINT2 + 92
#define WM_PUSH_PRINT_LOG_FILE_USBPRINT			WM_IST_PRINT2 + 93
#define WM_ALL_PRINT_LOG_END_USBPRINT			WM_IST_PRINT2 + 94
#define WM_PRINT_FLAG_USBPRINT					WM_IST_PRINT2 + 95

//成绩单导入工具
#define WM_PRINT_TRANSCRIPT_DB_INFO				WM_IST_PRINT2 + 100 //数据库配置信息
#define WM_PRINT_TRANSCRIPT_TOOL_LOGON			WM_IST_PRINT2 + 101 //管理员登录

//打印日志-离校单打印
#define WM_REQ_PRINT_LOG_LEAVESCHOOL				WM_IST_PRINT2 + 110
#define WM_REQ_PRINT_LOG_FILE_LEAVESCHOOL			WM_IST_PRINT2 + 111
#define WM_REQ_PRINT_LOG_FILE_END_LEAVESCHOOL		WM_IST_PRINT2 + 112
#define WM_PUSH_PRINT_LOG_FILE_LEAVESCHOOL			WM_IST_PRINT2 + 113
#define WM_ALL_PRINT_LOG_END_LEAVESCHOOL			WM_IST_PRINT2 + 114
#define WM_PRINT_FLAG_LEAVESCHOOL					WM_IST_PRINT2 + 115
#define WM_REQ_PRINT_LOG_LEAVESCHOOL_ENTRUST		WM_IST_PRINT2 + 116

//打印日志-云打印
#define WM_REQ_PRINT_LOG_CLOUD						WM_IST_PRINT2 + 120	//请求打印任务
#define WM_REQ_PRINT_LOG_FILE_CLOUD					WM_IST_PRINT2 + 121	//请求打印文件
#define WM_REQ_PRINT_LOG_FILE_END_CLOUD				WM_IST_PRINT2 + 122	//请求打印文件结束
#define WM_PUSH_PRINT_LOG_FILE_CLOUD				WM_IST_PRINT2 + 123	//推送云打印
#define WM_ALL_PRINT_LOG_END_CLOUD					WM_IST_PRINT2 + 124	//所有云打印完成
#define WM_PRINT_FLAG_CLOUD							WM_IST_PRINT2 + 125	//云打印标记
#define WM_PRINT_STATION_DEL_JOB_CLOUD				WM_IST_PRINT2 + 126	//打印站点删除云打印作业

//打印日志-公告打印
#define WM_REQ_PRINT_LOG_NOTICE					    WM_IST_PRINT2 + 130
#define WM_REQ_PRINT_LOG_FILE_NOTICE			    WM_IST_PRINT2 + 131
#define WM_REQ_PRINT_LOG_FILE_END_NOTICE		    WM_IST_PRINT2 + 132
#define WM_PUSH_PRINT_LOG_FILE_NOTICE			    WM_IST_PRINT2 + 133
#define WM_ALL_PRINT_LOG_END_NOTICE				    WM_IST_PRINT2 + 134
#define WM_PRINT_FLAG_NOTICE					    WM_IST_PRINT2 + 135

//成绩、证件、公告打印快照
#define WM_PRINT_SNAPSHOOT_LOG					    WM_IST_PRINT2 + 140
#define WM_PRINT_SNAPSHOOT_FILE_BEGIN			    WM_IST_PRINT2 + 141
#define WM_PRINT_SNAPSHOOT_FILE_DATA			    WM_IST_PRINT2 + 142
#define WM_PRINT_SNAPSHOOT_FILE_END					WM_IST_PRINT2 + 143
#define WM_ALL_PRINT_SNAPSHOO_END				    WM_IST_PRINT2 + 144
#define WM_PRINT_FLAG_SNAPSHOOT						WM_IST_PRINT2 + 145


//打印小票
#define WM_TICKET_REQ_PURCHASE_LOG				    WM_IST_PRINT2 + 150
#define WM_TICKET_UPLOAD_PURCHASE_LOG			    WM_IST_PRINT2 + 151
#define WM_TICKET_UPDATE_PURCHASE_LOG			    WM_IST_PRINT2 + 152


#define WM_PRINT_PHONE_CHARGE					    WM_IST_PRINT2 + 200	//移动支付
#define WM_PRINT_PHONE_LOGIN						WM_IST_PRINT2 + 201	//移动登录


//webinf通知服务器
#define WM_WEB_NOTIFY_SERVER_REQ					WM_IST_PRINT2 + 300	//web请求服务器
#define WM_WEB_NOTIFY_SERVER_ACK					WM_IST_PRINT2 + 301 //web请求服务器之后服务器的回应
#define WM_SERVER_NOTIFY_PRT                        WM_IST_PRINT2 + 302 //服务器通知打印站点

#define WM_PRINT_STATTON_REQ_ORDER					WM_IST_PRINT2 + 400	//请求定单信息

#define WM_PRINT_PRINTER_METER_INFO					WM_IST_PRINT2 + 501 //打印机抄表信息
#define WM_PRINT_SHARE_PRINTER_INFO					WM_IST_PRINT2 + 502	//共享打印机信息

//客户端
#define WM_Client_Close_Connect						WM_IST_PRINT2 + 601	//打印客户端关闭连接
#define WM_Client_Re_Connect						WM_IST_PRINT2 + 602	//打印客户端重新连接
#define WM_Client_RefreshLoginQRCode				WM_IST_PRINT2 + 603	//打印客户端刷新登录二维码


#endif