#ifndef __MULTI_LANGUAGE_DEF_H__
#define __MULTI_LANGUAGE_DEF_H__

#define MLLMS	CMultiLanguage::GetInstance().GetString

enum UiLanguage
{
	UILANG_CHINESE	= 0,	//中文显示
	UILANG_ENGLISH	= 1		//英文显示
};

//Welcome界面
#define WelcomeSystemInitFail			TEXT("WelcomeSystemInitFail")
#define WelcomeCardInitFail				TEXT("WelcomeCardInitFail")
#define WelcomeConnectingServer			TEXT("WelcomeConnectingServer")
#define WelcomeConnectedServer			TEXT("WelcomeConnectedServer")
#define WelcomeSystemIniting			TEXT("WelcomeSystemIniting")
#define WelcomeSystemInitingException	TEXT("WelcomeSystemInitingException")
#define WelcomePrintstationOutOfTime	TEXT("WelcomePrintstationOutOfTime")
#define WelcomePrinterStateOffline		TEXT("WelcomePrinterStateOffline")
#define WelcomePrinterStateNoPaper		TEXT("WelcomePrinterStateNoPaper")
#define WelcomePrinterStateNoInk		TEXT("WelcomePrinterStateNoInk")
#define WelcomePrinterStatePaperJam		TEXT("WelcomePrinterStatePaperJam")
#define WelcomePrinterStateOutNet		TEXT("WelcomePrinterStateOutNet")
#define WelcomePrinterStatePaused		TEXT("WelcomePrinterStatePaused")
#define WelcomePrinterStateNotAvaliable		TEXT("WelcomePrinterStateNotAvaliable")
#define WelcomeSwitchLanguage			TEXT("WelcomeSwitchLanguage")
#define WelcomeCopyExceptionTip			TEXT("WelcomeCopyExceptionTip")


//Printloginpage界面
#define PrintLoginSendLoginRequestFail	TEXT("PrintLoginSendLoginRequestFail")
#define PrintLoginUserNameCanntEmpty	TEXT("PrintLoginUserNameCanntEmpty")
#define PrintLoginLogining				TEXT("PrintLoginLogining")
#define PrintLoginVerifying				TEXT("PrintLoginVerifying")
#define PrintLoginReduceMoneyFromCardFailReTry	TEXT("PrintLoginReduceMoneyFromCardFailReTry")
#define PrintLoginAccountLeftMoneyNotEnough		TEXT("PrintLoginAccountLeftMoneyNotEnough")
#define PrintLoginFailedPassWord		TEXT("PrintLoginFailedPassWord")
#define PrintLoginUserOrCardNotExist	TEXT("PrintLoginUserOrCardNotExist")
#define PrintLoginUserNoRightAccess		TEXT("PrintLoginUserNoRightAccess")
#define PrintLoginUserHasForbidden		TEXT("PrintLoginUserHasForbidden")
#define PrintLoginUiTitle				TEXT("PrintLoginUiTitle")
#define PrintLoginUiCardNo				TEXT("PrintLoginUiCardNo")
#define PrintLoginUiPwd					TEXT("PrintLoginUiPwd")
#define PrintLoginUiCancel				TEXT("PrintLoginUiCancel")
#define PrintLoginUiOk					TEXT("PrintLoginUiOk")
#define PrintLoginUiSoftKeyboard		TEXT("PrintLoginUiSoftKeyboard")
#define PrintLoginUiDealLoginOperate	TEXT("PrintLoginUiDealLoginOperate")
#define PrintLoginUiFailTips			TEXT("PrintLoginUiFailTips")
#define PrintLoginUiFailTips2			TEXT("PrintLoginUiFailTips2")
#define PrintLoginUiFailTips3			TEXT("PrintLoginUiFailTips3")
#define PrintLoginOpException			TEXT("PrintLoginOpException")

//Pprintopage界面
#define PrintOpUiPrintPreView			TEXT("PrintOpUiPrintPreView")
#define PrintOpUiDocList				TEXT("PrintOpUiDocList")
#define PrintOpUiPrint					TEXT("PrintOpUiPrint")
#define PrintOpUiDuplexPrint			TEXT("PrintOpUiDuplexPrint")
#define PrintOpUiRefresh				TEXT("PrintOpUiRefresh")
#define PrintOpUiDelete					TEXT("PrintOpUiDelete")
#define PrintOpUiPreviousPage			TEXT("PrintOpUiPreviousPage")
#define PrintOpUiNextPage				TEXT("PrintOpUiNextPage")
#define PrintOpUiZoomIn					TEXT("PrintOpUiZoomIn")
#define PrintOpUiZoomOut				TEXT("PrintOpUiZoomOut")
#define PrintOpUiFitPage				TEXT("PrintOpUiFitPage")
#define PrintOpUiFullSize				TEXT("PrintOpUiFullSize")
#define PrintOpUiPrinted				TEXT("PrintOpUiPrinted")
#define PrintOpUiSubmissionTime			TEXT("PrintOpUiSubmissionTime")
#define PrintOpUiDocName				TEXT("PrintOpUiDocName")
#define PrintOpUiDocPages				TEXT("PrintOpUiDocPages")
#define PrintOpUiDocCopies				TEXT("PrintOpUiDocCopies")
#define PrintOpUiPaperType				TEXT("PrintOpUiPaperType")
#define PrintOpUiPrintType				TEXT("PrintOpUiPrintType")
#define PrintOpUiPrintNormal			TEXT("PrintOpUiPrintNormal")
#define PrintOpUiPrintBreakPoint		TEXT("PrintOpUiPrintBreakPoint")
#define PrintOpUiColorPrint				TEXT("PrintOpUiColorPrint")
#define PrintOpUiExit					TEXT("PrintOpUiExit")
#define PrintOpUiCheckAll				TEXT("PrintOpUiCheckAll")
#define PrintOpUiNoCheckAll				TEXT("PrintOpUiNoCheckAll")
#define PrintOpUiChecked				TEXT("PrintOpUiChecked")
#define PrintOpUiNoCheck				TEXT("PrintOpUiNoCheck")
#define PrintOpUiRevDataAndWait			TEXT("PrintOpUiRevDataAndWait")
#define PrintOpUiConfirmDeleteNoPrintedJob		TEXT("PrintOpUiConfirmDeleteNoPrintedJob")
#define PrintOpUiConfirmDeletePrintedJob		TEXT("PrintOpUiConfirmDeletePrintedJob")
#define PrintOpUiCharging						TEXT("PrintOpUiCharging")
#define PrintOpUiJobPagesExceededLimit			TEXT("PrintOpUiJobPagesExceededLimit")
#define PrintOpUiNetErrChargeFailAndReTry		TEXT("PrintOpUiNetErrChargeFailAndReTry")
#define PrintOpUiAccountNoMoneyAndRecharge		TEXT("PrintOpUiAccountNoMoneyAndRecharge")
#define PrintOpUiCardNoMoneyAndRecharge			TEXT("PrintOpUiCardNoMoneyAndRecharge")
#define PrintOpUiCardReduceMoneyFail			TEXT("PrintOpUiCardReduceMoneyFail")
#define PrintOpUiReduceMoneySucc				TEXT("PrintOpUiReduceMoneySucc")
#define PrintOpUiExceptionAdnReduceMoneyFail	TEXT("PrintOpUiExceptionAdnReduceMoneyFail")
#define PrintOpUiPrinting						TEXT("PrintOpUiPrinting")
#define PrintOpUiPrintComplete					TEXT("PrintOpUiPrintComplete")
#define PrintOpUiPrintedAndBreakOff				TEXT("PrintOpUiPrintedAndBreakOff")
#define PrintOpUiHaveNoMoney					TEXT("PrintOpUiHaveNoMoney")
#define PrintOpUiCardReduceFailReScan			TEXT("PrintOpUiCardReduceFailReScan")
#define PrintOpUiNetException					TEXT("PrintOpUiNetException")
#define PrintOpUiPrintCompleteChargeing			TEXT("PrintOpUiPrintCompleteChargeing")
#define PrintOpUiPrintMonitorStart				TEXT("PrintOpUiPrintMonitorStart")
#define PrintOpUiPrintMonitorPrinting			TEXT("PrintOpUiPrintMonitorPrinting")
#define PrintOpUiPrintMonitorEnd				TEXT("PrintOpUiPrintMonitorEnd")
#define PrintOpUiFmDocName						TEXT("PrintOpUiFmDocName")
#define PrintOpUiFmCurrentPages					TEXT("PrintOpUiFmCurrentPages")
#define PrintOpUiFmRateTypeStation				TEXT("PrintOpUiFmRateTypeStation")
#define PrintOpUiFmRateTypeDept					TEXT("PrintOpUiFmRateTypeDept")
#define PrintOpUiFmRateTypeUser					TEXT("PrintOpUiFmRateTypeUser")
#define PrintOpUiFmRateA3HB						TEXT("PrintOpUiFmRateA3HB")
#define PrintOpUiFmRateA3Color					TEXT("PrintOpUiFmRateA3Color")
#define PrintOpUiFmRateA4HB						TEXT("PrintOpUiFmRateA4HB")
#define PrintOpUiFmRateA4Color					TEXT("PrintOpUiFmRateA4Color")
#define PrintOpUiFmAccountLeftMoney				TEXT("PrintOpUiFmAccountLeftMoney")
#define PrintOpUiFmAccountSubsidyMoney			TEXT("PrintOpUiFmAccountSubsidyMoney")
#define PrintOpUiFmPrintingIndex				TEXT("PrintOpUiFmPrintingIndex")
#define PrintOpUiFmPrintedIndex					TEXT("PrintOpUiFmPrintedIndex")
#define PrintOpUiFmPrintedErr					TEXT("PrintOpUiFmPrintedErr")
#define PrintOpUiFmPrintedAppCancel				TEXT("PrintOpUiFmPrintedAppCancel")
#define PrintOpUiFmPrintedUserCancel			TEXT("PrintOpUiFmPrintedUserCancel")
#define PrintOpUiFmPrintedHDNoSpace				TEXT("PrintOpUiFmPrintedHDNoSpace")
#define PrintOpUiFmPrintedMemNoSpace			TEXT("PrintOpUiFmPrintedMemNoSpace")
#define PrintOpUiFmPrintedUnknowErr				TEXT("PrintOpUiFmPrintedUnknowErr")
#define PrintOpUiFmExitTimeOut					TEXT("PrintOpUiFmExitTimeOut")
#define PrintOpUiPrintNoPaper					TEXT("PrintOpUiPrintNoPaper")
#define PrintOpUiPrintNoJobFile					TEXT("PrintOpUiPrintNoJobFile")
#define PrintOpUiPreViewNoJobFile				TEXT("PrintOpUiPreViewNoJobFile")


//copyscanpage界面
#define CopyScanUiSelfCopy			TEXT("CopyScanUiSelfCopy")
#define CopyScanUiUserRate			TEXT("CopyScanUiUserRate")
#define CopyScanUiDeptRate			TEXT("CopyScanUiDeptRate")
#define CopyScanUiStationRate		TEXT("CopyScanUiStationRate")
#define CopyScanUiCardNo			TEXT("CopyScanUiCardNo")
#define CopyScanUiName				TEXT("CopyScanUiName")
#define CopyScanUiAccountLeftMoney	TEXT("CopyScanUiAccountLeftMoney")
#define CopyScanUiAccountSubsidyMoney			TEXT("CopyScanUiAccountSubsidyMoney")
#define CopyScanUiRateType			TEXT("CopyScanUiRateType")
#define CopyScanUiA3Color			TEXT("CopyScanUiA3Color")
#define CopyScanUiA3HB				TEXT("CopyScanUiA3HB")
#define CopyScanUiA4Color			TEXT("CopyScanUiA4Color")
#define CopyScanUiA4HB				TEXT("CopyScanUiA4HB")
#define CopyScanUiTime				TEXT("CopyScanUiTime")
#define CopyScanUiPaperType			TEXT("CopyScanUiPaperType")
#define CopyScanUiPapers			TEXT("CopyScanUiPapers")
#define CopyScanUiPrice				TEXT("CopyScanUiPrice")
#define CopyScanUiHB				TEXT("CopyScanUiHB")
#define CopyScanUiColor				TEXT("CopyScanUiColor")
#define CopyScanUiTotal				TEXT("CopyScanUiTotal")
#define CopyScanUiSelfScan			TEXT("CopyScanUiSelfScan")
#define CopyScanUiPaperRate			TEXT("CopyScanUiPaperRate")
#define CopyScanUiColorRate			TEXT("CopyScanUiColorRate")
#define CopyScanUiHBRate			TEXT("CopyScanUiHBRate")
#define CopyScanUiColorType			TEXT("CopyScanUiColorType")
#define CopyScanUiSize				TEXT("CopyScanUiSize")
#define CopyScanUiExit				TEXT("CopyScanUiExit")
#define CopyScanUiExitTimeOut		TEXT("CopyScanUiExitTimeOut")
#define CopyScanUiAccountLeftMoneyNotEnough	TEXT("CopyScanUiAccountLeftMoneyNotEnough")
#define CopyScanUiCardReduceFailReScan		TEXT("CopyScanUiCardReduceFailReScan")
#define CopyScanUiNetErr					TEXT("CopyScanUiNetErr")
#define CopyScanUiChargeFail				TEXT("CopyScanUiChargeFail")

//云打印界面
#define CloudPrintUiPrintAll		TEXT("CloudPrintUiPrintAll")
#define CloudPrintUiPrintDup		TEXT("CloudPrintUiPrintDup")
#define CloudPrintUiDupSimplex		TEXT("CloudPrintUiDupSimplex")
#define CloudPrintUiDupVertical		TEXT("CloudPrintUiDupVertical")
#define CloudPrintUiDupHorizontal	TEXT("CloudPrintUiDupHorizontal")
#define CloudPrintUiPrintOrient		TEXT("CloudPrintUiPrintOrient")
#define CloudPrintUiOrientPortrait	TEXT("CloudPrintUiOrientPortrait")
#define CloudPrintUiOrientLandscape	TEXT("CloudPrintUiOrientLandscape")
#define CloudPrintUiDealDate		TEXT("CloudPrintUiDealDate")

//刷卡、扫二维码扣费
#define ChargePageUiTitle			TEXT("ChargePageUiTitle")
#define ChargePageUiTips			TEXT("ChargePageUiTips")
#define ChargePageUiTipsCheckDebt	TEXT("ChargePageUiTipsCheckDebt")
#define ChargePageUiTipsScan		TEXT("ChargePageUiTipsScan")
#define ChargePageUiExit			TEXT("ChargePageUiExit")
#define ChargePageUiExitTimeOut		TEXT("ChargePageUiExitTimeOut")
#define ChargePageUiReLogin			TEXT("ChargePageUiReLogin")
#define ChargePageUiOpFailAndContactAdmin	TEXT("ChargePageUiOpFailAndContactAdmin")
#define ChargePageUiOpSuccAndContinue		TEXT("ChargePageUiOpSuccAndContinue")
#define ChargePageUiNotCurrentUserOrCard	TEXT("ChargePageUiNotCurrentUserOrCard")
#define ChargePageUiCharging				TEXT("ChargePageUiCharging")
#define ChargePageUiNetWorkException		TEXT("ChargePageUiNetWorkException")
#define ChargePageUiCardReduceFail			TEXT("ChargePageUiCardReduceFail")

//显示图片资源
#define PrintStationOemPictureHelp				TEXT("PrintStationOemPictureHelp")
#define PrintStationOemPictureHelpKeyDown		TEXT("PrintStationOemPictureHelpKeyDown")
#define PrintStationOemPictureAlarm				TEXT("PrintStationOemPictureAlarm")
#define PrintStationOemPictureAlarmKeyDown		TEXT("PrintStationOemPictureAlarmKeyDown")
#define PrintStationOemPictureCancel			TEXT("PrintStationOemPictureCancel")
#define PrintStationOemPictureCancelKeyDown		TEXT("PrintStationOemPictureCancelKeyDown")
#define PrintStationOemPictureOK				TEXT("PrintStationOemPictureOK")
#define PrintStationOemPictureOKKeyDown			TEXT("PrintStationOemPictureOKKeyDown")
#define PrintStationOemPicturePrint				TEXT("PrintStationOemPicturePrint")
#define PrintStationOemPicturePrintKeyDown		TEXT("PrintStationOemPicturePrintKeyDown")
#define PrintStationOemPictureCopy				TEXT("PrintStationOemPictureCopy")
#define PrintStationOemPictureCopyKeyDown		TEXT("PrintStationOemPictureCopyKeyDown")
#define PrintStationOemPictureScan				TEXT("PrintStationOemPictureScan")
#define PrintStationOemPictureScanKeyDown		TEXT("PrintStationOemPictureScanKeyDown")
#define PrintStationOemPictureCloudPrint		TEXT("PrintStationOemPictureCloudPrint")
#define PrintStationOemPictureCloudPrintKeyDown	TEXT("PrintStationOemPictureCloudPrintKeyDown")
//显示图片资源还有其它的,目前先使用这些,以后再完善

//代缴费
#define BillPaymentUiRevDataAndWait				TEXT("BillPaymentUiRevDataAndWait")
#define BillPaymentUiRevDataFail				TEXT("BillPaymentUiRevDataFail")
#define BillPaymentUiNoSelAndSelOneType			TEXT("BillPaymentUiNoSelAndSelOneType")
#define BillPaymentUiGetInfoFailAndRetry		TEXT("BillPaymentUiGetInfoFailAndRetry")
#define BillPaymentUiSelTypeHasCompAndSelOther	TEXT("BillPaymentUiSelTypeHasCompAndSelOther")
#define BillPaymentUiChargePromptMessage		TEXT("BillPaymentUiChargePromptMessage")
#define BillPaymentUiChargeSucc					TEXT("BillPaymentUiChargeSucc")
#define BillPaymentUiChargeSuccButNetErrAndNoRetry	TEXT("BillPaymentUiChargeSuccButNetErrAndNoRetry")
#define BillPaymentUiChargeFailAndReScanCard	TEXT("BillPaymentUiChargeFailAndReScanCard")
#define BillPaymentUiChargeType					TEXT("BillPaymentUiChargeType")
#define BillPaymentUiChargeMoney				TEXT("BillPaymentUiChargeMoney")
#define BillPaymentUiChargeState				TEXT("BillPaymentUiChargeState")
#define BillPaymentUiChargeStateComplete		TEXT("BillPaymentUiChargeStateComplete")
#define BillPaymentUiChargeStateNoComplete		TEXT("BillPaymentUiChargeStateNoComplete")
#define BillPaymentUiChargeAmount				TEXT("BillPaymentUiChargeAmount")
#define BillPaymentUiExit						TEXT("BillPaymentUiExit")
#define BillPaymentUiFmExitTimeOut				TEXT("BillPaymentUiFmExitTimeOut")

//USB打印
#define UsbPrintUiDealingPdfFileAndWaiting		TEXT("UsbPrintUiDealingPdfFileAndWaiting")
#define UsbPrintUiDealingWordFileAndWaiting		TEXT("UsbPrintUiDealingWordFileAndWaiting")
#define UsbPrintUiDealingExcelFileAndWaiting	TEXT("UsbPrintUiDealingExcelFileAndWaiting")
#define UsbPrintUiDealingPptFileAndWaiting		TEXT("UsbPrintUiDealingPptFileAndWaiting")
#define UsbPrintUiDealingImageFileAndWaiting	TEXT("UsbPrintUiDealingImageFileAndWaiting")
#define UsbPrintUiReadingUsbDevice				TEXT("UsbPrintUiReadingUsbDevice")
#define UsbPrintUiNotFindUsbDevice				TEXT("UsbPrintUiNotFindUsbDevice")


#endif